language: node_js

services:
  - docker

script:
- docker build -t node-ci-cd-example .
- docker run -d node-ci-cd-example
- docker ps -a

deploy:
  provider: script
  script: bash docker_push
  on:
    branch: master
